### ISSUE TITLE
Failure to Generate nation

### ISSUE THREAD

**Issue by bobpoplol** [elmokki/nationgen#1191]
I open up the nationgen file and get it to run but when I starts to run nation generation it fails and this is what it says.

Dominions 5 NationGen version 0.7.0-RC7 (6th of May 2018)
------------------------------------------------------------------
SETTING advancedDescs WAS NOT DEFINED!
SETTING basicDescs WAS NOT DEFINED!
Loading settings... java.io.FileNotFoundException: /private/var/folders/2v/xnjngmyd0631zt8q62sr7lyw0000gn/T/hsperfdata_nicwilson/settings.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at nationGen.Settings.<init>(Settings.java:161)
	at nationGen.NationGen.<init>(NationGen.java:105)
	at nationGen.GUI.GUI.process(GUI.java:390)
	at nationGen.GUI.GUI.actionPerformed(GUI.java:473)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
done!
Loading Larzm42's Dom5 Mod Inspector database... java.io.FileNotFoundException: /private/var/folders/2v/xnjngmyd0631zt8q62sr7lyw0000gn/T/hsperfdata_nicwilson/units.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.elmokki.Dom3DB.<init>(Dom3DB.java:68)
	at nationGen.NationGen.loadDom3DB(NationGen.java:388)
	at nationGen.NationGen.<init>(NationGen.java:111)
	at nationGen.GUI.GUI.process(GUI.java:390)
	at nationGen.GUI.GUI.actionPerformed(GUI.java:473)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Error loading file /private/var/folders/2v/xnjngmyd0631zt8q62sr7lyw0000gn/T/hsperfdata_nicwilson/units.csv (No such file or directory)
java.io.FileNotFoundException: /private/var/folders/2v/xnjngmyd0631zt8q62sr7lyw0000gn/T/hsperfdata_nicwilson/forbidden_ids.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at nationGen.IdHandler.loadFile(IdHandler.java:102)
	at nationGen.NationGen.generate(NationGen.java:193)
	at nationGen.NationGen.generate(NationGen.java:163)
	at nationGen.GUI.GUI$3.run(GUI.java:424)
Generating 1 nations with seed -324362599.
Generating nations...
- Generating nation 1/1 (seed -1722691172)... Exception in thread "Thread-0" java.lang.NullPointerException
	at nationGen.nation.Nation.getRaces(Nation.java:167)
	at nationGen.nation.Nation.generate(Nation.java:524)
	at nationGen.nation.Nation.<init>(Nation.java:130)
	at nationGen.NationGen.generate(NationGen.java:240)
	at nationGen.NationGen.generate(NationGen.java:163)
	at nationGen.GUI.GUI$3.run(GUI.java:424)

**Comment by RiritoNinigaya** [comment]
Try Reinstall Java

**Comment by elmokki** [comment]
Actually, I think it's been extracted wrong. There should be better error handling for that.

``SETTING advancedDescs WAS NOT DEFINED!
SETTING basicDescs WAS NOT DEFINED!
Loading settings... java.io.FileNotFoundException: /private/var/folders/2v/xnjngmyd0631zt8q62sr7lyw0000gn/T/hsperfdata_nicwilson/settings.txt (No such file or directory)``

This sounds like it just can't find settings.txt, which is supposed to be in the working directory, ie same directory as nationgen.jar

**Comment by RiritoNinigaya** [comment]
okay
