### ISSUE TITLE
IllegalArgumentException during generation

### ISSUE THREAD

**Issue by HenrikTipp** [elmokki/nationgen#1214]
On 
Seed: 4494577357309175933
Setting code: 10
Generating 64 Nations stops on the 10th nation (seed -481578633434581877)

> Loading Larzm42's Dom6 Mod Inspector database... done!
> Loading definitions... done!
> Generating 64 nations with seed 4494577357309175933.
> Generating nations...
> - Successfully generated nation 1/64 (seed -6767762301995207331)
> - Successfully generated nation 2/64 (seed -5520830625151457961)
> - Successfully generated nation 3/64 (seed -2541452789002165209)
> - Successfully generated nation 4/64 (seed -7152079633752070310)
> - Successfully generated nation 5/64 (seed 5926500668511829671)
> - Successfully generated nation 6/64 (seed 4260233542795117596)
> - Successfully generated nation 7/64 (seed 2183466823939137074)
> - Successfully generated nation 8/64 (seed -7861066844218112062)
> - Successfully generated nation 9/64 (seed -9120717258950772752)
> - Successfully generated nation 10/64 (seed -481578633434581877)
> java.lang.IllegalArgumentException: Mount named demonbred_hog could not be found.
> 	at nationGen.NationGen.lambda$14(NationGen.java:935)
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> 	at nationGen.NationGen.handleMount(NationGen.java:934)
> 	at nationGen.NationGen.handleMounts(NationGen.java:807)
> 	at nationGen.NationGen.polishNation(NationGen.java:746)
> 	at nationGen.NationGen.generate(NationGen.java:251)
> 	at nationGen.NationGen.generate(NationGen.java:112)
> 	at nationGen.GUI.GUI.lambda$2(GUI.java:385)
> 	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by danieldelpercio** [comment]
Duplicate of https://github.com/elmokki/nationgen/issues/1211 , should be fixed in current version.
