### ISSUE TITLE
0.6.9 crash during generation

### ISSUE THREAD

**Issue by TomClancyIsDead** [elmokki/nationgen#372]
Setting 5

Generating 40 nations with seed 997930217.
Generating nations..........................Exception in thread "Thread-2" java.lang.NullPointerException
	at nationGen.magic.MageGenerator.handleGiveToAll(MageGenerator.java:1555)
	at nationGen.magic.MageGenerator.applyFilters(MageGenerator.java:1542)
	at nationGen.rostergeneration.HeroGenerator.generateMageHero(HeroGenerator.java:181)
	at nationGen.rostergeneration.HeroGenerator.generateHeroes(HeroGenerator.java:44)
	at nationGen.nation.Nation.generate(Nation.java:338)
	at nationGen.nation.Nation.<init>(Nation.java:105)
	at nationGen.NationGen.generate(NationGen.java:209)
	at nationGen.NationGen.generate(NationGen.java:159)
	at nationGen.GUI.GUI$5.run(GUI.java:420)

**Comment by elmokki** [comment]
It would seem that a hero mage is getting an empty filter because it's supposed to get a really strong filter but while strong filters are available, it is eligible for none of them. Interestingly there was a failsafe in place but it was only for the other filter allocation method.

Thanks for the report.
